name: Eleventy Build

on:
  push:
    branches: [$default-branch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
      
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.4.0'
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

deploy:
  environment:
    name: github-pages
    url: ${{ steps.deploy.outputs_url }}
  needs: build
  runs-on: ubuntu-latest
  name: Deploy
  steps:
    - name: Deploy to GitHub Pages
    id: deploy
    uses: actions/deploy-pages@v4
